import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";
import { verifyPrivyToken } from "@/lib/privy-server";

const anthropic = new Anthropic();

const SYSTEM_PROMPT = `You write one-line teasers for paywalled posts.

Rules:
- Output exactly one sentence, under 160 characters.
- Tempt the reader. Do not reveal the thesis, conclusion, or any punchline.
- Match the source's tone (casual stays casual, technical stays technical).
- Use the same language as the source.
- Never start with "In this post", "This article", "Today", or any meta-language.
- No emojis. No surrounding quotes.
- Output the sentence ONLY — no preamble, no explanation.`;

const MAX_INPUT_CHARS = 4000;

/**
 * POST /api/preview
 * Body: { content: string }
 *
 * Returns { preview: string } — a one-line teaser generated by Claude
 * from the gated content. Privy-authed to avoid burning API credit on
 * anonymous traffic.
 */
export async function POST(req: NextRequest) {
  const claims = await verifyPrivyToken(req.headers.get("authorization"));
  if (!claims) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }

  if (
    !process.env.ANTHROPIC_API_KEY ||
    process.env.ANTHROPIC_API_KEY.startsWith("PASTE_")
  ) {
    return NextResponse.json(
      { error: "ANTHROPIC_API_KEY not configured" },
      { status: 500 }
    );
  }

  let body: { content?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const content = body.content?.trim() ?? "";
  if (content.length < 30) {
    return NextResponse.json(
      { error: "Content too short to summarize (min 30 chars)" },
      { status: 400 }
    );
  }

  const truncated =
    content.length > MAX_INPUT_CHARS
      ? content.slice(0, MAX_INPUT_CHARS) + "\n\n[...]"
      : content;

  try {
    const msg = await anthropic.messages.create({
      model: "claude-sonnet-4-5",
      max_tokens: 200,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: truncated }],
    });

    const text = msg.content
      .map((b) => (b.type === "text" ? b.text : ""))
      .join("")
      .trim()
      // Strip any stray surrounding quotes the model still adds occasionally
      .replace(/^["'""'']|["'""'']$/g, "")
      .trim();

    if (!text) {
      return NextResponse.json(
        { error: "Model returned no text" },
        { status: 502 }
      );
    }
    // Clamp to 240 chars (matches Post.preview validation max)
    const clamped = text.length > 240 ? text.slice(0, 237) + "…" : text;
    return NextResponse.json({ preview: clamped });
  } catch (e) {
    console.error("[api/preview]", e);
    const message =
      e instanceof Error ? e.message : "Anthropic API error";
    return NextResponse.json({ error: message }, { status: 502 });
  }
}
